In [1]:
# SECTION A: Data Structures and Control Structures

In [2]:
#1.LIST OPERATIONS

list = [10, 20, 30, 40, 50]
print(f"ORIGINAL LIST elements : {list}")

print("-- APPEND --")
list.append(60)
print(list) 

print("-- EXTEND --")
list.extend([70, 80])
print(list)

print("-- INSERT --")
list.insert(0, 100)
print(list) 

print("-- REMOVE --")
list.remove(70)
print(list) 

print("-- POP --")
list.pop()
print(list)  

print("-- INDEX --")
print(list.index(40))

print("-- COUNT --")
print(list.count(10)) 

print("-- SORT --")
list.sort()
print(list)

print("-- REVERSE --")
list.reverse()
print(list) 

print("-- CLEAR --")
list.clear()
print(list) 

ORIGINAL LIST elements : [10, 20, 30, 40, 50]
-- APPEND --
[10, 20, 30, 40, 50, 60]
-- EXTEND --
[10, 20, 30, 40, 50, 60, 70, 80]
-- INSERT --
[100, 10, 20, 30, 40, 50, 60, 70, 80]
-- REMOVE --
[100, 10, 20, 30, 40, 50, 60, 80]
-- POP --
[100, 10, 20, 30, 40, 50, 60]
-- INDEX --
4
-- COUNT --
1
-- SORT --
[10, 20, 30, 40, 50, 60, 100]
-- REVERSE --
[100, 60, 50, 40, 30, 20, 10]
-- CLEAR --
[]


In [3]:
#2.TUPLE EXPLANATION

stds=("IYLU","IYBUN","BUNNY")
print(stds)
print(len(stds))
stds[1]="PRANAV" 
print(stds)

('IYLU', 'IYBUN', 'BUNNY')
3


TypeError: 'tuple' object does not support item assignment

In [4]:
#2.TUPLE IMMUTABILITY

stds=("IYLU","IYBUN","BUNNY")
print(stds)
print(len(stds))
try:
    stds[1]="PRANAV" #immutable
    print(stds)
except TypeError as e:
    print("Error: ",e)


('IYLU', 'IYBUN', 'BUNNY')
3
Error:  'tuple' object does not support item assignment


In [5]:
#3.SET WITH DUPLICATES

S = {10,20,30,20,40,10,50}
print("SET :",S)

SET : {50, 20, 40, 10, 30}


In [6]:
#4.DICTIONARY OPERATIONS

dict={"NAME ":"PRANAV","AGE ":21,"CITY ":"KADAPA"}
print("-- DATA --")
print(dict)
dict["AGE "]=22
dict["GMAIL "]= "pranavsaiobili4@gmail.com"
print("-- UPDATED DATA --")
print(dict)

-- DATA --
{'NAME ': 'PRANAV', 'AGE ': 21, 'CITY ': 'KADAPA'}
-- UPDATED DATA --
{'NAME ': 'PRANAV', 'AGE ': 22, 'CITY ': 'KADAPA', 'GMAIL ': 'pranavsaiobili4@gmail.com'}


In [7]:
#5.VOTING ELIGIBILITY CHECK

age=int(input("YOUR AGE : "))
if age>=18 :
    print("You are eligible to vote :)")
else:
    print("You are not eligible to vote :(")
    

YOUR AGE :  40


You are eligible to vote :)


In [8]:
#6.GRADE SYSTEM

marks=int(input("Enter your marks to know your grade :"))
if marks>=90 :
    print("GRADE A")
elif(marks>=75 and marks<=89):
    print("GRADE B")
elif(marks>= 50 and marks<=74):
    print("GRADE C")
elif(marks< 50):
    print("FAIL")
    

Enter your marks to know your grade : 89


GRADE B


In [9]:
#7.POSITIVE EVEN or ODD

num=int(input("Enter Number: "))
if num>0 :
    if(num%2==0) :
        print("+ve even ")
    else:
        print("+ve odd")
elif num==0 :
    print("ZERO-0")
else:
    print("-ve")

Enter Number:  99


+ve odd


In [10]:
#SECTION B: NumPy

In [11]:
#8.NUMPY ILLUSTRATION

import numpy as np

arr=np.array(5)
arr1d=np.array([1,2,3,4,5])
arr2d=np.array([[10,20,30],[40,50,60]])

print("ARRAY: ",arr)
print("1D-ARRAY: \n",arr1d)
print("2d-ARRAY: \n",arr2d)

ARRAY:  5
1D-ARRAY: 
 [1 2 3 4 5]
2d-ARRAY: 
 [[10 20 30]
 [40 50 60]]


In [12]:
#9.RANDAM 4X4 ARRAY

import random

arr = np.random.randint(0,100,(4, 4))
print("Random 4x4 array : \n ",arr)

Random 4x4 array : 
  [[16 90 98 97]
 [94 38 45 94]
 [95 69 31  4]
 [63 61 86 57]]


In [13]:
#10.NUMPY TO PANDAS

import pandas as pd

arr2d=([[10,20,30],[40,50,60],[70,80,90]])
df=pd.DataFrame(arr2d,columns=['A','B','C'])
print("DATA FRAME :\n",df)

DATA FRAME :
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [14]:
# Section C: Pandas

In [15]:
# 11.EXPLORING PANDAS


data = {
    'Name': ['iylu','pranav','bunny','praneetha','dhanush','abhishek','prem','tharun','sudheer','kiran'],
    'Age': [21, 22, 20, 21, 22, 21, 23, 23, 24, 23],
    'City': ['HYD','CHE','MUM','BLR','PUN','HYD','CHE','HYD','DEL','MUM'],
    'Salary': [25000,30000,28000,35000,30000,np.nan,30000,25000,np.nan,28000]
}
df=pd.DataFrame(data)
print("-- DATA -- \n",df)
print("-- INFO -- \n",df.info())
print("-- DESCRIBE -- \n",df.describe())
print("-- NAME and CITYc--",df[["Name","City"]])
udf=df.drop("City",axis=1)
print("\n-- AFTER DROPPING CITY --\n", udf)
udf['Salary']=udf['Salary'].fillna(udf["Salary"].mean())
print("-- MISSING VALUES FILLED WITH MEAN -- \n",udf)
uqdf=udf.drop_duplicates()
print("-- UNIQUE -- \n",uqdf)
      



-- DATA -- 
         Name  Age City   Salary
0       iylu   21  HYD  25000.0
1     pranav   22  CHE  30000.0
2      bunny   20  MUM  28000.0
3  praneetha   21  BLR  35000.0
4    dhanush   22  PUN  30000.0
5   abhishek   21  HYD      NaN
6       prem   23  CHE  30000.0
7     tharun   23  HYD  25000.0
8    sudheer   24  DEL      NaN
9      kiran   23  MUM  28000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
-- INFO -- 
 None
-- DESCRIBE -- 
              Age        Salary
count  10.000000      8.000000
mean   22.000000  28875.000000
std     1.247219   3226.563851
min    20.000000  25000.000000
25%    21.000000  27250.000000
50%    22.000000  29000.